import assert from 'node:assert/strict';
import { clamp, laneFromX, rectsOverlap, scoreTick, grade, LANES, playerYForHeight, currentMission, missionProgress, isMissionComplete, applyCollision, completeMission } from '../src/engine.js';

assert.equal(LANES.length, 3);
assert.equal(clamp(5, 0, 3), 3);
assert.equal(clamp(-1, 0, 3), 0);
assert.equal(laneFromX(10, 300), 0);
assert.equal(laneFromX(150, 300), 1);
assert.equal(laneFromX(290, 300), 2);
assert.equal(rectsOverlap({x:0,y:0,w:20,h:20},{x:10,y:10,w:20,h:20}), true);
assert.equal(rectsOverlap({x:0,y:0,w:5,h:5},{x:10,y:10,w:5,h:5}), false);
assert.ok(playerYForHeight(700) <= 572, 'player should stay above bottom controls/browser bar');
assert.ok(playerYForHeight(520) < 520, 'player must be visible on short screens');
let state = {level:0, missionCoins:6, missionNitro:0, missionDistance:0, combo:1, score:0, health:2, nitro:10, chase:50};
assert.equal(currentMission(0).city, 'الرياض');
assert.equal(missionProgress(state), 6);
assert.equal(isMissionComplete(state), true);
assert.equal(completeMission(state), true);
assert.equal(state.level, 1);
assert.ok(state.score >= 1200);
assert.ok(state.chase < 50);
state = {shield:1, health:3, combo:4, chase:20, score:0};
assert.equal(applyCollision(state), 'shield');
assert.equal(state.health, 3);
state = {shield:0, health:1, combo:4, chase:90, score:0};
assert.equal(applyCollision(state), 'gameover');
const s = scoreTick({speed:400,distance:0,missionDistance:0,score:0,combo:2,level:1,chase:20,boost:0}, 1);
assert.ok(s.distance > 390);
assert.ok(s.score > 0);
assert.ok(s.chase > 20);
assert.equal(grade(19000), 'ملك المطاردة');
console.log('chase arcade tests passed');
